### ISSUE TITLE
`docs/conf.py` should have current year for copyright

### ISSUE THREAD

**Issue by dstansby** [napari/cookiecutter-napari-plugin#114]
Currently the copyright variable is `copyright = "2015, David Stansby"`, I presume because 2015 was when this `conf.py` file was generated.

I might be worth investigating whether a new `conf.py` file should be generated that more recent than 2015 too!

**Comment by tlambert03** [comment]
yeah, the whole sphinx template is probably very outdated... I would actually vote that we don't provide a "choose docs" option at all, instead, pointing people to the documentation for sphinx or jupyter book (otherwise, we're pretty much taking on the job of keeping those docs templates up to date all the time, which is not the purpose here)
