### ISSUE TITLE
Add dependabot to the generated plugins?

### ISSUE THREAD

**Issue by cnstt** [napari/cookiecutter-napari-plugin#120]

**Comment by tlambert03** [comment]
Hi @cnstt, would you like to add a little context here?
My first thought is "probably: no ... but curious to hear your thoughts".
For me, dependabot has been very useful in app-like settings, where I'm hard-pinning my requirements, but would like to know a) if an update is generally available and b) if there's a security risk in one of my pinned dependencies.  However, in a python-based ecosystem (with a flat package tree, where there's only 1 version of a given package installed at any given time), having plugins hard-pin dependencies, or even give very narrow compatibility ranges is _very_ problematic, since one plugin can very easily break another.

thoughts?

**Comment by tlambert03** [comment]
have a look into it.  If you can find a configurable that restricts the scope to github actions deps or development dependencies (but probably _not_ python deps), that could be interesting

**Comment by Czaki** [comment]
@tlambert03 There you have PartSeg configuration where dependabot is for GitHub actions and pyinstaller requirements (for reproducible bundle build). By removing the first entry you will get only GitHub actions. 

https://github.com/4DNucleome/PartSeg/blob/84fea4e120629d5a528708e4c7b7921d19524331/.github/dependabot.yml

**Comment by tlambert03** [comment]
what do you think @Czaki, should we add something here?  other @napari/core-devs ?

**Comment by alisterburt** [comment]
Seems useful! If we add it it should probably be optional though

**Comment by Czaki** [comment]
dependabot does not change your code, it only creates pull requests. 

> if you add things, new users will say "this is too complicated, can't you just provide me a simple napari plugin template?"

Did we want to simplify entry or make it a little complicated, but increase code quality.

I today feel confused reading this article: https://www.frontiersin.org/articles/10.3389/fcomp.2022.931939/full where they mention napari with `ZELDA` plugin (that I meat first time)  that metadata declares that it is python 3.8 only, but its readme suggest that it works with python 3.8.  

So if we do not put enough requirements on entry then we may end with multiple unmaintained/low-quality plugins that may introduce the impression that you need to be an expert to use napari. And addressing this may require creating another team that will curate napari plugins and verifies them to provide information to a user if he should try this plugin. 

As a workaround maybe we could hide pre-commit and dependabot under one question?

**Comment by alisterburt** [comment]
Thanks for enumerating, it's tough! I do like napari as a vehicle for discovery of this tooling, it was my introduction to testing and deployment on github actions but I also agree we want the on-ramp to be as gradual as possible

Let's err on the side of simple and point at cool shiny things in the docs :-)
