### ISSUE TITLE
BSD-3 copyright holder replaced by plugin name

### ISSUE THREAD

**Issue by guiwitz** [napari/cookiecutter-napari-plugin#137]
I was wondering why GitHub wasn't recognising my license as BSD-3 generated by this cookiecutter, and while investigating I found that the "copyright holder" in the BSD-3 section "Neither the name of the copyright holder nor the names of its
  contributors etc." is replaced by the plugin name. This looks wrong as the copyright holder is not the plugin name, and popular packages like Numpy or scikit-image actually use the copyright holder name there (e.g. Numpy Team). Was this made on purpose or is it an error? In the latter case, it's probably worth fixing, as many plugins on the napari hub use this default.

(FYI, I still don't know why GitHub doesn't recognise the license as BSD-3.)

**Comment by Czaki** [comment]
could you point your repository?

**Comment by Czaki** [comment]
using tool from this stackoverflow https://stackoverflow.com/questions/66258037/github-license-not-recognised the core of the problem is that you have copyright author in two lines. 

It looks like you meet some variant of https://github.com/licensee/licensee/issues/554

When put all copyright in one line, then the match is 100%.

**Comment by guiwitz** [comment]
Thanks for your help, this indeed fixed the problem on Github!

I'm still not sure though about the "copyholder" thing from the cookiecutter.
