### ISSUE TITLE
cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.

### ISSUE THREAD

**Issue by haesleinhuepf** [napari/cookiecutter-napari-plugin#22]
Hi @tlambert03 ,

I was hitting the same error for a couple of times and I'm wondering if it's worth mentioning the solution in the readme, e.g. in the section about using git. As Windows user who doesn't do `git` via command line routinely, I receive this error message:

```
> cookiecutter https://github.com/napari/cookiecutter-napari-plugin

[...]

cookiecutter.exceptions.VCSNotInstalled: 'git' is not installed.
```

The simplest solution is obviously `conda install git`. Using [git for windows](https://git-scm.com/download/win) is also possible but more complicated because you need to add git to the PATH.

Cheers,
Robert

**Comment by tlambert03** [comment]
I’m conflicted about these sorts of thing (though willing to do it if everyone else agrees). 

The problem in my opinion is that if we add a small note about every edge case that a user might run into, then the readme/docs turn into a wall of text that is an immediate TLDR.
It’s one thing if there are cryptic message, but “git is not installed” is pretty clear.  I don’t know, I just struggle a bit with adding things like “how to install/use x” to our docs when the first hit on google will likely answer it. (This same concept comes up a lot for me with pytest, where I don’t want to literally duplicate their docs in our docs just because people may use pytest with napari)

Again, if there’s strong support for adding this, I’m ok with it, but I don’t think it’s necessarily a no brainer

**Comment by haesleinhuepf** [comment]
> I don’t think it’s necessarily a no brainer

I agree. And many other napari developers also know what git is and how to install it for sure. It depends on the target audience of this repo. If you want to motivate image analysts who provide scripts to end-users to make napari-plugins out of their scripts: I know a lot of image analysts with and without python skills who still don't use git at all. ;-)

> the first hit on google will likely answer it.

Unfortunately, the first three hits don't suggest conda and point to more complicated solutions. 
That's why I created this issue. 
![image](https://user-images.githubusercontent.com/12660498/115020580-126ae380-9ebb-11eb-90a6-90710ec471eb.png)


I have no strong opinion here btw. Looking forward to hear other's opinions.

**Comment by jni** [comment]
I'm in the middle also... At least having this issue open might help some of the more persistent people... 😅

**Comment by haesleinhuepf** [comment]
Actually, that's a cookiecutter problem. They should have "git" as a dependency and install it, which is not possible via pip I guess.
However, in context of [this idea / PR](https://github.com/clEsperanto/napari_pyclesperanto_assistant/pull/15) the issue becomes mine. ;-)

![image](https://user-images.githubusercontent.com/12660498/115511660-60983200-a281-11eb-8653-fc65a7c6f148.png)

![image](https://user-images.githubusercontent.com/12660498/115511841-9b9a6580-a281-11eb-87e6-f23b36c7d2a1.png)

But I guess, I will just write a page about all that at some point and send people there...
