### ISSUE TITLE
consider github template instead of cookiecutter

### ISSUE THREAD

**Issue by tlambert03** [napari/cookiecutter-napari-plugin#55]
don't have a well-informed opinion at this point, but it might be worth considering creating a github template repository for napari plugins:
https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository

cc @DragaDoncila

**Comment by tlambert03** [comment]
eh... prolly not.  i can't find many ways to customize it like we do here.

**Comment by jni** [comment]
LOL! tbh I would love it. It involves more manual labor but it's easier for a newbie. I wouldn't do it instead of but in addition to...

**Comment by DragaDoncila** [comment]
Hmmm...

@jni I can *kinda* see the argument that it's easier for a newbie because they don't have to `pip install` anything (although realistically, they probably will if they're writing a plugin) or use the terminal...? Is that why you think it's easier?

But the main issue with the repository template, as @tlambert03 pointed out, is that you basically can't customize anything, you just get all the files as is. That means we have to document for the user all the different places they'll need to go and change things: the module name, the package name, the author information, all the project url stuff, deleting files they don't want (e.g. I only want a reader so I have to go delete the rest), and soon deleting stuff in the manifest that points to files they don't want. 

We could avoid some of that by having separate repositories for readers, writers, dock widgets, etc. but then you can't have a combo? Given all of that, I don't know how it could possibly be easier for newbie. But, maybe I'm confused or not seeing something obvious

**Comment by GenevieveBuckley** [comment]
> LOL! tbh I would love it. It involves more manual labor but it's easier for a newbie. I wouldn't do it instead of but in addition to...

I think we want to stick with having one preferred way to do things, as much as possible. I'd want a really compelling reason before adding more options to do basically the same thing. Disadvantages include: causing more confusion, having the less used option get less love/upkeep, and making it harder to figure out why people might be running into issues.
